version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: react-dom
    versions:
    - 17.0.1
